# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:54
from __future__ import unicode_literals

from django.db import migrations

#from movieratings.models import Rating, User, Movie

def pullmovies(apps, schema_editor):
    Movie = apps.get_model('movieratings', 'Movie')
    with open("u.item", encoding='iso-8859-1') as movies:
        for movie in movies.readlines():
            line = movie.split('|')
            Movie.objects.create(
                id=line[0],
                title=line[1],
                release_date=line[2],
                video_release_date=line[3],
                imdb_url=line[4],
                unknown_genre=line[5],
                action=line[6],
                adventure=line[7],
                animation=line[8],
                childrens=line[9],
                comedy=line[10],
                crime=line[11],
                documentary=line[12],
                drama=line[13],
                fantasy=line[14],
                film_noir=line[15],
                horror=line[16],
                musical=line[17],
                mystery=line[18],
                romance=line[19],
                sci_fi=line[20],
                thriller=line[21],
                war=line[22],
                western=line[23]
                )
def pulluser(apps, schema_editor):
    User = apps.get_model('movieratings', 'User')


    with open("u.user") as users:
        for user in users.readlines():
            line = user.split('|')
            User.objects.create(
                pk=line[0],
                age=line[1],
                gender=line[2]
            )

def pulldata(apps, schema_editor):
    Movie = apps.get_model('movieratings', 'Movie')
    User = apps.get_model('movieratings', 'User')
    Rating = apps.get_model('movieratings', 'Rating')

    with open("u.data") as udata:
        for ratings in udata.readlines():
            line = ratings.split('\t')
            user = User.objects.get(id=line[0])
            movie = Movie.objects.get(id=line[1])
            Rating.objects.create(
                user=user,
                movie=movie,
                rating=int(line[2])
            )
    # raise Exception("ULTRAMAXIMUMFAILLLLLLLLL!!!!!!!")


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(pullmovies),
        migrations.RunPython(pulluser),
        migrations.RunPython(pulldata)
    ]
