# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20160225_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_release_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
