# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_auto_20160225_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),

    ]
