# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 03:13
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0004_user_occupation'),
    ]

    operations = [


    ]
